// You can replace this with a larger list; keep words UPPERCASE 5 letters
window.WORDLEISH_ANSWERS = [
  "ARISE","TEACH","LIGHT","SHARE","CRANE","PLANT","BRAVE","QUICK","SWEET","SMILE",
  "TRACK","CLOUD","MANGO","NERVE","DRINK","SUGAR","METAL","RIVER","ROUTE","SCORE",
  "EARTH","HEART","POINT","SOUND","NINJA","PARTY","FAITH","CHAIR","STONE","TIGER",
  "PANDA","WATER","HONEY","PIXEL","FRAME","PEACH","BREAD","PHONE","CABLE","ULTRA",
  "ALPHA","NORTH","SOUTH","EASTS","WESTS","OTHER","WORDS","LOREM","IPSUM"
];
