// You can replace this with a larger list; keep words UPPERCASE 5 letters
window.WORDLEISH_ANSWERS = [
  "ARISE","TEACH","LIGHT","SHARE","CRANE","PLANT","BRAVE","QUICK","SWEET","SMILE",
  "TRACK","CLOUD","MANGO","NERVE","DRINK","SUGAR","METAL","RIVER","ROUTE","SCORE",
  "EARTH","HEART","POINT","SOUND","NINJA","PARTY","FAITH","CHAIR","STONE","TIGER",
  "PANDA","WATER","HONEY","PIXEL","FRAME","PEACH","BREAD","PHONE","CABLE","ULTRA",
  "ALPHA","NORTH","SOUTH","EASTS","WESTS","OTHER","WORDS","LOREM","IPSUM","aback", "abase", "abate", "abbey", "abbot", "abide", "abled", "about", "above", "abuse",
  "acorn", "acrid", "actor", "acute", "adage", "adapt", "adept", "admin", "admit", "adopt",
  "adult", "affix", "again", "agent", "agile", "aging", "agree", "ahead", "aisle", "alarm",
  "album", "alert", "alien", "align", "alike", "alive", "alloy", "allow", "alone", "along",
  "altar", "alter", "amaze", "amber", "ample", "angel", "anger", "angle", "angry", "apart",
  "apple", "apply", "apron", "arena", "argue", "arise", "armor", "arose", "array", "arrow",
  "aside", "asset", "audio", "audit", "avoid", "awake", "award", "aware", "awful", "axiom",
  "bacon", "badge", "bagel", "baker", "balmy", "banjo", "basic", "batch", "beach", "beard",
  "beast", "begin", "being", "belly", "below", "bench", "berry", "birth", "black", "blade",
  "blame", "blank", "blast", "blaze", "bleak", "blend", "bless", "blind", "blink", "block",
  "blood", "bloom", "blown", "board", "boast", "bonus", "boost", "booth", "bound", "brain",
  "brake", "brand", "brave", "bread", "break", "breed", "brick", "bride", "brief", "bring",
  "broad", "broke", "brown", "brush", "buddy", "build", "built", "bunch", "burst", "buyer",
  "cabin", "cable", "camel", "candy", "canoe", "carry", "carve", "cause", "cease", "chain",
  "chair", "chant", "chaos", "charm", "chart", "chase", "cheap", "cheat", "check", "cheek",
  "cheer", "chess", "chest", "chief", "child", "chill", "china", "choir", "chose", "chunk",
  "cigar", "claim", "class", "clean", "clear", "clerk", "click", "cliff", "climb", "clock",
  "close", "cloth", "cloud", "coach", "coast", "color", "comic", "coral", "couch", "could",
  "count", "court", "cover", "crack", "craft", "crash", "crazy", "cream", "creek", "crest",
  "crime", "crisp", "cross", "crowd", "crown", "crush", "curve", "cycle"
];
